nexy_slack:
  # If you want to use an another httplug client service.
  http:
    client: httplug.client

  # The Slack API Incoming WebHooks URL.
  endpoint:             'https://hooks.slack.com/services/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'
  channel:              null
  username:             null
  icon:                 null
  link_names:           false
  unfurl_links:         false
  unfurl_media:         true
  allow_markdown:       true
  markdown_in_attachments: []